version: '3'

services:
  api:
    build:
      dockerfile: ./docker/develop/Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
      - mysql
    environment:
      - PORT=3000
    env_file:
      - .env
    ports:
      - '${PORT:-3000}:3000'
  redis:
    image: 'redis:alpine'
    volumes:
      - redis:/data
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s
  mysql:
    image: mysql:8
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}']
      retries: 3
      timeout: 5s
volumes:
  redis:
    driver: local
  mysql:
    driver: local
